data:
  dataset_name: "PartNetE"
  base_path: "./data/PartNetE"

render:
  camera_distance: 2.0
  resolution: [800, 800]
  num_cameras: 15

model:
  glip_weight_path: "/data/xhhuang/project/PartSTAD/models/glip_large_model.pth"
  sam_weight_path: "/data/xhhuang/project/PartSTAD/segment-anything/models/sam_vit_h_4b8939.pth"
  sam_model_type: "vit_h"

algorithm:
  iou_threshold: 0.3
  min_cluster_points: 50

mllm:
  provider: "openai"
  model_name: "gemini-3-flash-preview"
  api_key_env: "API_KEY"
  base_url: "https://yibuapi.com/v1"
